us_company_stock_data = [
    {"company_name": "Apple Inc.", "stock_name": "AAPL"},
    {"company_name": "Microsoft Corporation", "stock_name": "MSFT"},
    {"company_name": "Amazon.com Inc.", "stock_name": "AMZN"},
    {"company_name": "Alphabet Inc. (Google)", "stock_name": "GOOGL"},
    {"company_name": "Meta Platforms Inc. (Facebook)", "stock_name": "META"},
    {"company_name": "Tesla Inc.", "stock_name": "TSLA"},
    {"company_name": "Berkshire Hathaway Inc.", "stock_name": "BRK.B"},
    {"company_name": "Johnson & Johnson", "stock_name": "JNJ"},
    {"company_name": "JPMorgan Chase & Co.", "stock_name": "JPM"},
    {"company_name": "Visa Inc.", "stock_name": "V"},
    {"company_name": "Procter & Gamble Co.", "stock_name": "PG"},
    {"company_name": "Walmart Inc.", "stock_name": "WMT"},
    {"company_name": "UnitedHealth Group Inc.", "stock_name": "UNH"},
    {"company_name": "Mastercard Incorporated", "stock_name": "MA"},
    {"company_name": "Home Depot Inc.", "stock_name": "HD"},
    {"company_name": "Intel Corporation", "stock_name": "INTC"},
    {"company_name": "Verizon Communications Inc.", "stock_name": "VZ"},
    {"company_name": "Coca-Cola Company", "stock_name": "KO"},
    {"company_name": "Walt Disney Company", "stock_name": "DIS"},
    {"company_name": "Cisco Systems Inc.", "stock_name": "CSCO"},
    {"company_name": "AT&T Inc.", "stock_name": "T"},
    {"company_name": "Pfizer Inc.", "stock_name": "PFE"},
    {"company_name": "Netflix Inc.", "stock_name": "NFLX"},
    {"company_name": "Oracle Corporation", "stock_name": "ORCL"},
    {"company_name": "Adobe Inc.", "stock_name": "ADBE"},
    {"company_name": "Abbott Laboratories", "stock_name": "ABT"},
    {"company_name": "NVIDIA Corporation", "stock_name": "NVDA"},
    {"company_name": "IBM Corporation", "stock_name": "IBM"},
    {"company_name": "Salesforce.com Inc.", "stock_name": "CRM"},
    {"company_name": "Exxon Mobil Corporation", "stock_name": "XOM"},
    {"company_name": "McDonald's Corporation", "stock_name": "MCD"},
    {"company_name": "Bank of America Corporation", "stock_name": "BAC"},
    {"company_name": "Chevron Corporation", "stock_name": "CVX"},
    {"company_name": "Wells Fargo & Co.", "stock_name": "WFC"},
    {"company_name": "Costco Wholesale Corporation", "stock_name": "COST"},
    {"company_name": "3M Company", "stock_name": "MMM"},
    {"company_name": "Johnson & Johnson", "stock_name": "JNJ"},
    {"company_name": "Walt Disney Company", "stock_name": "DIS"},
    {"company_name": "Goldman Sachs Group Inc.", "stock_name": "GS"},
    {"company_name": "Intel Corporation", "stock_name": "INTC"},
    {"company_name": "Bristol-Myers Squibb Company", "stock_name": "BMY"},
    {"company_name": "Caterpillar Inc.", "stock_name": "CAT"},
    {"company_name": "United Technologies Corporation", "stock_name": "UTX"},
    {"company_name": "American Express Company", "stock_name": "AXP"},
    {"company_name": "Honeywell International Inc.", "stock_name": "HON"},
    {"company_name": "Merck & Co. Inc.", "stock_name": "MRK"},
    {"company_name": "Medtronic plc", "stock_name": "MDT"},
    {"company_name": "Lowe's Companies Inc.", "stock_name": "LOW"},
    {"company_name": "Philip Morris International Inc.", "stock_name": "PM"},
    {"company_name": "Nike Inc.", "stock_name": "NKE"},
]